[package]
name = "verificador_de_cpf"
version = "0.1.0"
authors = ["ciro"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
